import {Inter} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='layoutStyle'>
          <title>QuickLearn</title>
          <ul className='navClass center'>
            <li className='nav'>
              <Link href={'/'}>About the App</Link>
            </li>
            <li className='nav'>
              <Link href={'/flashcardsets'}>View Flashcards</Link>
            </li>
            <li className='nav'>
              <Link href={'/flashcardsets/new'}>Add Flashcard Set</Link>
            </li>
            <li className='nav'>
              <Link href={'/flashcards/new'}>Add Flashcard</Link>
            </li>
            <li className='nav'>
              <Link href={'/flashcardsets/delete'}>Delete Flashcard Set</Link>
            </li>
            <li className='nav'>
              <Link href={'/flashcards/delete'}>Delete Flashcard</Link>
            </li>
          </ul>
          {children}
        </main>
      </body>
    </html>
  );
}
